// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7kEo7BpUcD-OPwCWCH5jPxcNInFFFZk',
    appId: '1:971529489544:web:28882692ce7154e9c7e33d',
    messagingSenderId: '971529489544',
    projectId: 'rando-oise-a4efa',
    authDomain: 'rando-oise-a4efa.firebaseapp.com',
    storageBucket: 'rando-oise-a4efa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCItS7HodcwuKMcg_gTn-pS2q4qh4qrg8',
    appId: '1:971529489544:android:86a095ec45bc9372c7e33d',
    messagingSenderId: '971529489544',
    projectId: 'rando-oise-a4efa',
    storageBucket: 'rando-oise-a4efa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Atg74m9W24YuD9jvf6H0pKYAJu2MQEM',
    appId: '1:971529489544:ios:c5daa3a8a5e8953ac7e33d',
    messagingSenderId: '971529489544',
    projectId: 'rando-oise-a4efa',
    storageBucket: 'rando-oise-a4efa.firebasestorage.app',
    iosBundleId: 'fr.randooise.randoUser',
  );
}
